[alias]
xtask = "run --package xtask --"
integration-test = "test --features integration --profile integration --workspace --test integration"

# By default, on musl linux, statically linked binaries are produced.
# But such binaries do not support loading libraries using `dlopen()` ("libloading" crate),
# which is required for loading treesitter grammars.
[target.'cfg(target_env = "musl")']
rustflags = "-C target-feature=-crt-static"
