[alias]
xtask = "run --package xtask --"
integration-test = "test --features integration --profile integration --workspace --test integration"

[target.aarch64-unknown-linux-musl]
# By default, on musl linux, statically linked binaries are produced.
# But such binaries do not support loading libraries using `dlopen()` ("libloading" crate),
# which is required for loading treesitter grammars.
rustflags = ["-C", "target-feature=-crt-static"]
